name: filmguru
description: Netguru Flutter recruitment app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.5
  freezed: ^2.3.2
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  rxdart: ^0.27.7
  fvm: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  build_test: ^2.1.6
  mockito: ^5.3.2
  bloc_test: ^9.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/mock/movies_response.json

flutter_intl:
  enabled: true
